default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: turing-portfolios_development
test:
  <<: *default
  database: turing-portfolios_test
production:
  <<: *default
  database: turing-portfolios_production
  username: turing-portfolios
  password: <%= ENV['TURING-PORTFOLIOS_DATABASE_PASSWORD'] %>
